# Generated by Django 6.0.2 on 2026-04-10 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('days_allowed', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('hire_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_employees', to='core.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.position')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('work_type', models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('assignment', 'Assignment'), ('exam', 'Exam/Test'), ('report', 'Report'), ('curriculum', 'Curriculum Document'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='teacher_submissions/')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Needs Revision')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_to', models.ForeignKey(blank=True, help_text='Head of Class or Director who receives this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_submissions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=True)),
                ('is_late', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', '-date'], name='employees_a_employe_b62a87_idx'), models.Index(fields=['date'], name='employees_a_date_b8bb7b_idx'), models.Index(fields=['is_present'], name='employees_a_is_pres_d2cb2a_idx'), models.Index(fields=['is_late'], name='employees_a_is_late_29fca5_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.leavetype')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'status'], name='employees_l_employe_cc1aa4_idx'), models.Index(fields=['status'], name='employees_l_status_c9461e_idx'), models.Index(fields=['-applied_on'], name='employees_l_applied_3db387_idx'), models.Index(fields=['start_date', 'end_date'], name='employees_l_start_d_844d5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('overall_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('goals_achievement', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('communication', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('teamwork', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('technical_skills', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comments', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['employee', '-created_at'], name='employees_p_employe_50b851_idx'), models.Index(fields=['-review_period_end'], name='employees_p_review__ae306e_idx'), models.Index(fields=['overall_rating'], name='employees_p_overall_4e9b53_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_status'], name='employees_e_employm_b2a249_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'employment_status'], name='employees_e_departm_ac5287_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employees_e_hire_da_c2151e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['-created_at'], name='employees_e_created_9cbbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='worksubmission',
            index=models.Index(fields=['teacher', 'status'], name='employees_w_teacher_1ebffc_idx'),
        ),
        migrations.AddIndex(
            model_name='worksubmission',
            index=models.Index(fields=['submitted_to', 'status'], name='employees_w_submitt_925da1_idx'),
        ),
        migrations.AddIndex(
            model_name='worksubmission',
            index=models.Index(fields=['status'], name='employees_w_status_6c9e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='worksubmission',
            index=models.Index(fields=['-submitted_at'], name='employees_w_submitt_c90a81_idx'),
        ),
        migrations.AddIndex(
            model_name='worksubmission',
            index=models.Index(fields=['work_type'], name='employees_w_work_ty_3ec15b_idx'),
        ),
    ]
