# Generated by Django 6.0.2 on 2026-04-10 14:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('college', 'College'), ('university', 'University'), ('combined', 'Combined')], db_index=True, max_length=20)),
                ('institution_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('religious', 'Religious'), ('international', 'International'), ('vocational', 'Vocational'), ('special_needs', 'Special Needs'), ('boarding', 'Boarding'), ('day', 'Day School'), ('mixed', 'Mixed')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('email_domain', models.CharField(db_index=True, default='school.edu', help_text='Email domain for school users (e.g., kawandass.edu)', max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of last payment', null=True)),
                ('next_payment_due_date', models.DateField(blank=True, help_text='Next payment due date', null=True)),
                ('is_access_blocked', models.BooleanField(default=False, help_text='Block access for unpaid schools')),
                ('payment_notes', models.TextField(blank=True, help_text='Notes about payment status')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subscription_start', models.DateField()),
                ('subscription_end', models.DateField()),
                ('max_students', models.IntegerField(default=1000)),
                ('max_staff', models.IntegerField(default=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='core_school_code_987360_idx'), models.Index(fields=['is_active'], name='core_school_is_acti_2e0f0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('level', models.IntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField(default=40)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.school')),
            ],
            options={
                'ordering': ['school', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.school')),
            ],
            options={
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=20)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(db_index=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('admission_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('suspended', 'Suspended'), ('expelled', 'Expelled')], db_index=True, default='active', max_length=20)),
                ('scholarship_status', models.CharField(choices=[('none', 'No Scholarship'), ('partial', 'Partial Scholarship'), ('full', 'Full Scholarship')], db_index=True, default='none', max_length=20)),
                ('scholarship_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('scholarship_remarks', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField()),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(db_index=True, max_length=15)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='student_documents/birth_certificates/')),
                ('previous_report_card', models.FileField(blank=True, null=True, upload_to='student_documents/report_cards/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='student_documents/transfers/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='student_documents/others/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.school')),
            ],
            options={
                'ordering': ['school', 'admission_number'],
            },
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['school', 'level'], name='core_grade_school__ae54fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school', 'is_active'], name='core_depart_school__6251b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'is_current'], name='core_academ_school__90a6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', '-start_date'], name='core_academ_school__654107_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='unique_current_year_per_school'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'status'], name='core_studen_school__daa2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'grade', 'status'], name='core_studen_school__6b87a8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'first_name', 'last_name'], name='core_studen_school__16002e_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'scholarship_status'], name='core_studen_school__5e263d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_number')},
        ),
    ]
