# Generated by Django 6.0.2 on 2026-04-10 14:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3'), ('annual', 'Annual')], max_length=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('library_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sports_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lab_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('uniform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.grade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.school')),
            ],
            options={
                'ordering': ['academic_year', 'grade', 'term'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('card', 'Card Payment')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.student')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feestructure')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship_discount', models.DecimalField(decimal_places=2, default=0, help_text='Scholarship discount amount', max_digits=10)),
                ('amount_after_scholarship', models.DecimalField(decimal_places=2, default=0, help_text='Amount after scholarship discount', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_balances', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_balances', to='core.student')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='fees.feestructure')),
            ],
            options={
                'ordering': ['student', 'fee_structure'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('last_sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_sequences', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_type', models.CharField(choices=[('minor', 'Minor Offense'), ('major', 'Major Offense'), ('warning', 'Warning'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('location', models.CharField(blank=True, help_text='Where the incident occurred', max_length=200)),
                ('action_taken', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('detention', 'Detention'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('community_service', 'Community Service'), ('parent_meeting', 'Parent Meeting'), ('counseling', 'Counseling')], max_length=30)),
                ('action_details', models.TextField(blank=True, help_text='Details of action taken')),
                ('start_date', models.DateField(blank=True, help_text='Start date for suspension/detention', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for suspension/detention', null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_date', models.DateField(blank=True, null=True)),
                ('parent_response', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipline_records', to='core.student')),
            ],
            options={
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('replaced', 'Replaced')], default='active', max_length=20)),
                ('barcode', models.CharField(blank=True, help_text='Barcode for scanning', max_length=100)),
                ('qr_code', models.CharField(blank=True, help_text='QR code data', max_length=200)),
                ('replacement_reason', models.TextField(blank=True, help_text='Reason for replacement if applicable')),
                ('replacement_fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_id_cards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='core.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['academic_year', 'grade'], name='fees_feestr_academi_31cf0c_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active'], name='fees_feestr_is_acti_c62141_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['-created_at'], name='fees_feestr_created_541e2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'grade', 'term')},
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', 'student', 'fee_structure'], name='payment_lookup'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', 'payment_status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', '-payment_date'], name='payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['school', 'receipt_number'], name='payment_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['-created_at'], name='payment_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_number'), name='unique_receipt_per_school'),
        ),
        migrations.AddIndex(
            model_name='feebalance',
            index=models.Index(fields=['student', 'is_paid'], name='fees_feebal_student_2da5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='feebalance',
            index=models.Index(fields=['is_paid', 'due_date'], name='fees_feebal_is_paid_43fc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='feebalance',
            index=models.Index(fields=['-created_at'], name='fees_feebal_created_e637db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feebalance',
            unique_together={('student', 'fee_structure')},
        ),
        migrations.AddIndex(
            model_name='receiptsequence',
            index=models.Index(fields=['school', 'year', 'month'], name='receipt_seq_lookup'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptsequence',
            unique_together={('school', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='studentdiscipline',
            index=models.Index(fields=['student', 'incident_date'], name='fees_studen_student_116461_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdiscipline',
            index=models.Index(fields=['incident_type'], name='fees_studen_inciden_a5dbfb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdiscipline',
            index=models.Index(fields=['resolved'], name='fees_studen_resolve_dacbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentidcard',
            index=models.Index(fields=['student', 'status'], name='fees_studen_student_a2210a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentidcard',
            index=models.Index(fields=['card_number'], name='fees_studen_card_nu_6eadea_idx'),
        ),
        migrations.AddIndex(
            model_name='studentidcard',
            index=models.Index(fields=['status'], name='fees_studen_status_139964_idx'),
        ),
    ]
