# Generated by Django 6.0.2 on 2026-02-25 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_student_allergies_student_birth_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_type', models.CharField(choices=[('minor', 'Minor Offense'), ('major', 'Major Offense'), ('warning', 'Warning'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('location', models.CharField(blank=True, help_text='Where the incident occurred', max_length=200)),
                ('action_taken', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('detention', 'Detention'), ('suspension', 'Suspension'), ('expulsion', 'Expulsion'), ('community_service', 'Community Service'), ('parent_meeting', 'Parent Meeting'), ('counseling', 'Counseling')], max_length=30)),
                ('action_details', models.TextField(blank=True, help_text='Details of action taken')),
                ('start_date', models.DateField(blank=True, help_text='Start date for suspension/detention', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for suspension/detention', null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_date', models.DateField(blank=True, null=True)),
                ('parent_response', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='fees.student')),
            ],
            options={
                'ordering': ['-incident_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'incident_date'], name='fees_studen_student_116461_idx'), models.Index(fields=['incident_type'], name='fees_studen_inciden_a5dbfb_idx'), models.Index(fields=['resolved'], name='fees_studen_resolve_dacbb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('replaced', 'Replaced')], default='active', max_length=20)),
                ('barcode', models.CharField(blank=True, help_text='Barcode for scanning', max_length=100)),
                ('qr_code', models.CharField(blank=True, help_text='QR code data', max_length=200)),
                ('replacement_reason', models.TextField(blank=True, help_text='Reason for replacement if applicable')),
                ('replacement_fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_id_cards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='fees.student')),
            ],
            options={
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='fees_studen_student_a2210a_idx'), models.Index(fields=['card_number'], name='fees_studen_card_nu_6eadea_idx'), models.Index(fields=['status'], name='fees_studen_status_139964_idx')],
            },
        ),
    ]
