# Generated by Django 6.0.2 on 2026-04-10 14:05

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_type', models.CharField(choices=[('daycare', 'Daycare/Childcare Center'), ('preschool', 'Preschool/Pre-K'), ('kindergarten', 'Kindergarten'), ('primary', 'Primary School (Grades 1-6)'), ('elementary', 'Elementary School (K-5)'), ('junior_primary', 'Junior Primary School'), ('middle_school', 'Middle School (Grades 6-8)'), ('junior_high', 'Junior High School (Grades 7-9)'), ('high_school', 'High School (Grades 9-12)'), ('senior_high', 'Senior High School (Grades 11-12)'), ('secondary', 'Secondary School (O-Level & A-Level)'), ('college', 'College'), ('university', 'University'), ('technical_college', 'Technical College'), ('vocational_college', 'Vocational College'), ('community_college', 'Community College'), ('polytechnic', 'Polytechnic Institute'), ('special_education', 'Special Education School'), ('stem_school', 'STEM School'), ('arts_school', 'Arts School'), ('music_school', 'Music Conservatory'), ('sports_academy', 'Sports Academy'), ('language_school', 'Language School'), ('international_school', 'International School'), ('montessori', 'Montessori School'), ('waldorf', 'Waldorf School'), ('catholic_school', 'Catholic School'), ('christian_school', 'Christian School'), ('islamic_school', 'Islamic School'), ('jewish_school', 'Jewish School'), ('buddhist_school', 'Buddhist School'), ('hindu_school', 'Hindu School'), ('charter_school', 'Charter School'), ('magnet_school', 'Magnet School'), ('homeschool_coop', 'Homeschool Cooperative'), ('online_school', 'Online/Virtual School'), ('microschool', 'Microschool'), ('adult_education', 'Adult Education Center'), ('continuing_ed', 'Continuing Education'), ('corporate_training', 'Corporate Training Center'), ('professional_development', 'Professional Development Institute'), ('military_academy', 'Military Academy'), ('boarding_school', 'Boarding School'), ('hospital_school', 'Hospital School'), ('prison_education', 'Correctional Education'), ('refugee_school', 'Refugee Education Center'), ('nursery', 'Nursery School'), ('combined', 'Combined School (Multiple Levels)')], max_length=50)),
                ('institution_type', models.CharField(choices=[('government', 'Government Institution'), ('private', 'Private Institution'), ('religious', 'Religious Institution'), ('international', 'International Institution'), ('vocational', 'Vocational/Technical Institution'), ('special_needs', 'Special Needs Institution'), ('boarding', 'Boarding Institution'), ('day', 'Day Institution'), ('mixed', 'Mixed (Day & Boarding)')], default='private', max_length=20)),
                ('school_motto', models.CharField(blank=True, max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('enable_subjects', models.BooleanField(default=True)),
                ('enable_exams', models.BooleanField(default=True)),
                ('enable_report_cards', models.BooleanField(default=True)),
                ('enable_library', models.BooleanField(default=False)),
                ('enable_transport', models.BooleanField(default=False)),
                ('enable_hostel', models.BooleanField(default=False)),
                ('enable_parent_portal', models.BooleanField(default=True)),
                ('enable_online_classes', models.BooleanField(default=False)),
                ('enable_research', models.BooleanField(default=False)),
                ('enable_departments', models.BooleanField(default=False)),
                ('enable_courses', models.BooleanField(default=False)),
                ('enable_semesters', models.BooleanField(default=False)),
                ('is_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_school', to='core.academicyear')),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('payment', 'Payment Recorded'), ('view', 'Viewed'), ('export', 'Exported')], max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_anonymised', models.BooleanField(default=False, help_text='User data anonymised for GDPR compliance')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_au_user_id_1110c4_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx'), models.Index(fields=['-timestamp'], name='accounts_au_timesta_40aa9a_idx'), models.Index(fields=['is_anonymised'], name='accounts_au_is_anon_9699fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_anonymised', models.BooleanField(default=False, help_text='User data anonymised for GDPR compliance')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_lo_user_id_42ec06_idx'), models.Index(fields=['status', '-timestamp'], name='accounts_lo_status_aebe05_idx'), models.Index(fields=['-timestamp'], name='accounts_lo_timesta_d82a57_idx'), models.Index(fields=['ip_address'], name='accounts_lo_ip_addr_51fef5_idx'), models.Index(fields=['is_anonymised'], name='accounts_lo_is_anon_80544a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Primary contact for this student')),
                ('can_pickup', models.BooleanField(default=True, help_text='Authorized to pick up student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.student')),
            ],
            options={
                'ordering': ['-is_primary_contact', 'relationship'],
                'indexes': [models.Index(fields=['parent'], name='accounts_pa_parent__55b6f4_idx'), models.Index(fields=['student'], name='accounts_pa_student_762fe4_idx'), models.Index(fields=['is_primary_contact'], name='accounts_pa_is_prim_8cf5a0_idx')],
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ParentTeacherMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('recipient_type', models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('replied', 'Replied')], default='unread', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('parent_message', models.ForeignKey(blank=True, help_text='Reply to this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.parentteachermessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student this message is about', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.student')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='accounts_pa_recipie_0313e9_idx'), models.Index(fields=['student', '-sent_at'], name='accounts_pa_student_b2cd62_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default=accounts.models.generate_employee_id, help_text='Auto-generated unique employee ID', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('admin', 'System Administrator'), ('registrar', 'Registrar'), ('director', 'Director'), ('dos', 'Director of Studies (DOS)'), ('head_of_class', 'Head of Class'), ('deputy_head_teacher', 'Deputy Head Teacher'), ('teacher', 'Teacher'), ('security', 'Security'), ('bursar', 'Bursar'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('receptionist', 'Receptionist'), ('librarian', 'Librarian'), ('nurse', 'Nurse'), ('parent', 'Parent'), ('student', 'Student'), ('staff', 'Staff')], default='staff', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('force_password_reset', models.BooleanField(default=False, help_text='Force user to reset password on next login')),
                ('class_name', models.CharField(blank=True, help_text='Class assigned to Head of Class or Teacher (e.g., Grade 1A, Grade 2B)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('school', models.ForeignKey(blank=True, help_text='School this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['employee_id'], name='accounts_us_employe_f8a1cf_idx'), models.Index(fields=['role'], name='accounts_us_role_e16858_idx'), models.Index(fields=['is_active_employee'], name='accounts_us_is_acti_a09e13_idx'), models.Index(fields=['school', 'role'], name='accounts_us_school__c18643_idx')],
            },
        ),
    ]
