# Generated by Django 6.0.2 on 2026-02-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role_auditlog_loginlog'),
        ('fees', '0004_student_allergies_student_birth_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery School'), ('primary', 'Primary School'), ('secondary', 'Secondary School (O-Level & A-Level)'), ('college', 'College'), ('university', 'University'), ('combined', 'Combined School (Multiple Levels)')], max_length=20)),
                ('school_motto', models.CharField(blank=True, max_length=200)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('enable_subjects', models.BooleanField(default=True)),
                ('enable_exams', models.BooleanField(default=True)),
                ('enable_report_cards', models.BooleanField(default=True)),
                ('enable_library', models.BooleanField(default=False)),
                ('enable_transport', models.BooleanField(default=False)),
                ('enable_hostel', models.BooleanField(default=False)),
                ('enable_parent_portal', models.BooleanField(default=True)),
                ('enable_online_classes', models.BooleanField(default=False)),
                ('enable_research', models.BooleanField(default=False)),
                ('enable_departments', models.BooleanField(default=False)),
                ('enable_courses', models.BooleanField(default=False)),
                ('enable_semesters', models.BooleanField(default=False)),
                ('is_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_school', to='fees.academicyear')),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configuration',
            },
        ),
    ]
