# Generated by Django 6.0.2 on 2026-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_schoolconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='institution_type',
            field=models.CharField(choices=[('government', 'Government Institution'), ('private', 'Private Institution'), ('religious', 'Religious Institution'), ('international', 'International Institution'), ('vocational', 'Vocational/Technical Institution'), ('special_needs', 'Special Needs Institution'), ('boarding', 'Boarding Institution'), ('day', 'Day Institution'), ('mixed', 'Mixed (Day & Boarding)')], default='private', max_length=20),
        ),
    ]
