"""
Django settings for workplace_system project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from workplace_system.env_config import EnvironmentConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Print configuration on startup
EnvironmentConfig.print_config()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = EnvironmentConfig.DEBUG

# Generate SECRET_KEY if not set (for deployment)
SECRET_KEY = EnvironmentConfig.SECRET_KEY
if not SECRET_KEY:
    import secrets
    SECRET_KEY = secrets.token_urlsafe(50)
    print(f"Generated new SECRET_KEY: {SECRET_KEY}")
    print("Please add this to your environment variables!")

# Validate production settings
if not DEBUG and EnvironmentConfig.IS_PRODUCTION:
    print("✅ Production mode enabled with DEBUG=False")
elif DEBUG and EnvironmentConfig.IS_PRODUCTION:
    raise ValueError(
        'CRITICAL SECURITY ERROR: DEBUG=True in production! '
        'This exposes sensitive information. Set DEBUG=False immediately.'
    )

ALLOWED_HOSTS = EnvironmentConfig.ALLOWED_HOSTS

# Custom Error Handlers - Never crash, always handle errors gracefully
handler404 = 'core.error_handlers.handle_404'
handler500 = 'core.error_handlers.handle_500'
handler403 = 'core.error_handlers.handle_403'
handler400 = 'core.error_handlers.handle_400'

# CSRF Settings
CSRF_COOKIE_SECURE = True if not DEBUG else False
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict' if not DEBUG else 'Lax'

# Development: Allow localhost
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost:8001',
        'http://127.0.0.1:8001',
        'http://localhost:3000',
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://*.onrender.com',
        'https://school-management-system-vipe.onrender.com',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'crispy_forms',
    'widget_tweaks',
    # 'django_ratelimit',  # Disabled - use custom rate limiting
    
    # Local apps - Core first
    'core',
    'subscriptions',  # SaaS subscription management
    'accounts',
    'employees',
    'fees',
    'academics',
    'library',
    'inventory',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.sync_manager.OfflineMiddleware',
    'core.middleware.TenantMiddleware',  # Multi-tenant isolation - CRITICAL
    'accounts.middleware.SchoolConfigurationMiddleware',  # School setup check
    # Temporarily disabled security middleware for CSRF debugging
    # 'workplace_system.ssl_middleware.HTTPSRedirectMiddleware',  # HTTPS enforcement
    # 'workplace_system.ssl_middleware.SecurityHeadersEnforcementMiddleware',  # Security headers
    # 'workplace_system.ssl_middleware.CookieSecurityMiddleware',  # Secure cookies
    # 'workplace_system.security_middleware.SecurityHeadersMiddleware',
    # 'workplace_system.security_middleware.RequestLoggingMiddleware',
    # 'workplace_system.security_middleware.SecurityAuditMiddleware',
    # 'workplace_system.security_middleware.XSSProtectionMiddleware',
    # 'workplace_system.security_middleware.ClickjackingProtectionMiddleware',
    # 'workplace_system.security_middleware.ContentSecurityPolicyMiddleware',
]

# Caching Configuration for High Performance
CACHES = EnvironmentConfig.get_cache_config()

# Session Configuration for Performance
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

ROOT_URLCONF = 'workplace_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Added templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'workplace_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration
DATABASES = {
    'default': EnvironmentConfig.get_database_config()
}

# Validate database configuration for production
if EnvironmentConfig.IS_PRODUCTION:
    # Check if we have a valid database configuration
    db_config = DATABASES['default']
    if not EnvironmentConfig.DATABASE_URL and not db_config.get('PASSWORD'):
        print("WARNING: No database configuration found. Using SQLite fallback.")
        # Fallback to SQLite for now to prevent deployment failure
        DATABASES['default'] = {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'ATOMIC_REQUESTS': True,
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms Configuration
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Custom User Model (if you have one)
# AUTH_USER_MODEL = 'accounts.User'  # Uncomment if you have a custom user model

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Email Configuration (single source of truth via EnvironmentConfig)
EMAIL_BACKEND = EnvironmentConfig.EMAIL_BACKEND
EMAIL_HOST = EnvironmentConfig.EMAIL_HOST
EMAIL_PORT = EnvironmentConfig.EMAIL_PORT
EMAIL_USE_TLS = EnvironmentConfig.EMAIL_USE_TLS
EMAIL_USE_SSL = EnvironmentConfig.EMAIL_USE_SSL
EMAIL_HOST_USER = EnvironmentConfig.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EnvironmentConfig.EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = EnvironmentConfig.DEFAULT_FROM_EMAIL



# Rate Limiting Configuration - using custom middleware
# RATELIMIT_ENABLE = not DEBUG
# RATELIMIT_USE_CACHE = 'default'
# RATELIMIT_VIEW = 'django_ratelimit.views.ratelimited'

# SSL/HTTPS Security Settings - CRITICAL FOR PRODUCTION
SECURE_SSL_REDIRECT = True if not DEBUG else False
SESSION_COOKIE_SECURE = True if not DEBUG else False
CSRF_COOKIE_SECURE = True if not DEBUG else False
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'
CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'Strict'

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = True if not DEBUG else False
SECURE_HSTS_PRELOAD = True if not DEBUG else False

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Proxy Settings (if behind reverse proxy like nginx)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Additional Security
SECURE_REDIRECT_EXEMPT = []  # No paths exempt from SSL redirect

# Database Query Optimization
# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': EnvironmentConfig.LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'simple',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': EnvironmentConfig.LOG_LEVEL,
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
import logging
logs_dir = BASE_DIR / 'logs'
logs_dir.mkdir(exist_ok=True)

# Performance Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

# Database Connection Pooling (PostgreSQL only)
# Values are already set in EnvironmentConfig.get_database_config()
DATABASES['default']['CONN_MAX_AGE'] = DATABASES['default'].get('CONN_MAX_AGE', 600)
DATABASES['default']['ATOMIC_REQUESTS'] = DATABASES['default'].get('ATOMIC_REQUESTS', True)

# Template Caching (for production)
if not DEBUG:
    TEMPLATES[0]['APP_DIRS'] = False
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]

# ============================================================================
# SAAS PLATFORM CONFIGURATION
# ============================================================================

# Site Configuration
SITE_NAME = os.environ.get('SITE_NAME', 'School Management System')
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', 'support@example.com')

# Email Configuration
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # Development default
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# Payment Gateway Configuration
PAYMENT_GATEWAY = EnvironmentConfig.PAYMENT_GATEWAY

# Stripe
STRIPE_PUBLIC_KEY = EnvironmentConfig.STRIPE_PUBLIC_KEY
STRIPE_SECRET_KEY = EnvironmentConfig.STRIPE_SECRET_KEY
STRIPE_WEBHOOK_SECRET = EnvironmentConfig.STRIPE_WEBHOOK_SECRET

# Flutterwave
FLUTTERWAVE_PUBLIC_KEY = os.environ.get('FLUTTERWAVE_PUBLIC_KEY', '')
FLUTTERWAVE_SECRET_KEY = os.environ.get('FLUTTERWAVE_SECRET_KEY', '')
FLUTTERWAVE_WEBHOOK_SECRET = os.environ.get('FLUTTERWAVE_WEBHOOK_SECRET', '')

# Paystack
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', '')

# Subscription Settings
DEFAULT_TRIAL_DAYS = int(os.environ.get('DEFAULT_TRIAL_DAYS', '14'))
SUBSCRIPTION_GRACE_PERIOD_DAYS = int(os.environ.get('SUBSCRIPTION_GRACE_PERIOD_DAYS', '3'))

# Feature Flags (Global defaults - can be overridden per plan)
DEFAULT_FEATURES = {
    'advanced_reports': False,
    'sms_integration': False,
    'bulk_export': False,
    'api_access': False,
    'custom_branding': False,
    'priority_support': False,
}


# Offline Sync Configuration
SYNC_SERVER_URL = os.environ.get('SYNC_SERVER_URL', None)
SYNC_ENABLED = os.environ.get('SYNC_ENABLED', 'True') == 'True'
SYNC_INTERVAL_MINUTES = int(os.environ.get('SYNC_INTERVAL_MINUTES', '15'))
