# Generated by Django 6.0.2 on 2026-04-10 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('college', 'College'), ('university', 'University'), ('all', 'All Levels')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('compulsory', 'Compulsory Subject'), ('optional', 'Optional Subject')], default='core', max_length=20)),
                ('level', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('college', 'College'), ('university', 'University'), ('all', 'All Levels')], default='all', max_length=20)),
                ('credit_hours', models.IntegerField(default=3, help_text='For college/university')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('cat', 'Continuous Assessment Test'), ('midterm', 'Mid-Term Exam'), ('final', 'Final Exam'), ('mock', 'Mock Exam'), ('bot', 'Beginning of Term'), ('eot', 'End of Term'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project'), ('presentation', 'Presentation'), ('practical', 'Practical Exam'), ('coursework', 'Coursework'), ('thesis', 'Thesis/Dissertation')], max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1 / Semester 1'), ('2', 'Term 2 / Semester 2'), ('3', 'Term 3')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('pass_marks', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1)])),
                ('weightage', models.DecimalField(decimal_places=2, default=100, help_text='Percentage weightage in final grade', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False, help_text='Results published to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.academicyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.grade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.academicyear')),
                ('from_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='core.grade')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_promotions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.student')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='core.grade')),
            ],
            options={
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods_per_week', models.IntegerField(default=5)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='core.grade')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allocations', to='academics.subject')),
            ],
            options={
                'ordering': ['grade', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classsubject')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GradeScaleRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, help_text='GPA point', max_digits=3)),
                ('description', models.CharField(max_length=100)),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='academics.gradescale')),
            ],
            options={
                'ordering': ['-min_percentage'],
                'unique_together': {('grade_scale', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1 / Semester 1'), ('2', 'Term 2 / Semester 2'), ('3', 'Term 3')], max_length=10)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, help_text='Grade Point Average', max_digits=3)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative GPA', max_digits=3)),
                ('overall_grade', models.CharField(blank=True, max_length=5)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('total_students', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('teacher_comment', models.TextField(blank=True)),
                ('headteacher_comment', models.TextField(blank=True)),
                ('promoted_to_next_class', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.academicyear')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('next_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_students', to='core.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student', 'academic_year'], name='academics_r_student_0485c5_idx'), models.Index(fields=['academic_year', 'term'], name='academics_r_academi_5c3497_idx')],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('sick', 'Sick')], db_index=True, default='present', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'ordering': ['-date', 'student'],
                'indexes': [models.Index(fields=['student', 'date'], name='academics_s_student_9c5582_idx'), models.Index(fields=['date', 'status'], name='academics_s_date_e620eb_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='academics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='academics.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'indexes': [models.Index(fields=['student', 'exam'], name='academics_m_student_b5b37d_idx'), models.Index(fields=['exam', 'subject'], name='academics_m_exam_id_5cbb53_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('marks_obtained__gte', 0)), name='marks_non_negative')],
                'unique_together': {('student', 'subject', 'exam')},
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'term'], name='academics_e_academi_ea39be_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['grade', 'subject'], name='academics_e_grade_i_9d7b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('grade', 'subject', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_subject', 'day_of_week', 'start_time')},
        ),
    ]
