# Generated by Django 6.0.2 on 2026-02-25 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('fees', '0004_student_allergies_student_birth_certificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('college', 'College'), ('university', 'University'), ('all', 'All Levels')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeScaleRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, help_text='GPA point', max_digits=3)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('sick', 'Sick')], default='present', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.RenameField(
            model_name='reportcard',
            old_name='average_marks',
            new_name='attendance_percentage',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='periods_per_week',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='fees.grade'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Results published to students'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='weightage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentage weightage in final grade', max_digits=5),
        ),
        migrations.AddField(
            model_name='mark',
            name='grade_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='mark',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mark',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='average_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative GPA', max_digits=3),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='days_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='days_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grade Point Average', max_digits=3),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='next_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_students', to='fees.grade'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='promoted_to_next_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('compulsory', 'Compulsory Subject'), ('optional', 'Optional Subject')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='credit_hours',
            field=models.IntegerField(default=3, help_text='For college/university'),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('college', 'College'), ('university', 'University'), ('all', 'All Levels')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('cat', 'Continuous Assessment Test'), ('midterm', 'Mid-Term Exam'), ('final', 'Final Exam'), ('mock', 'Mock Exam'), ('bot', 'Beginning of Term'), ('eot', 'End of Term'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('project', 'Project'), ('presentation', 'Presentation'), ('practical', 'Practical Exam'), ('coursework', 'Coursework'), ('thesis', 'Thesis/Dissertation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1 / Semester 1'), ('2', 'Term 2 / Semester 2'), ('3', 'Term 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='overall_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1 / Semester 1'), ('2', 'Term 2 / Semester 2'), ('3', 'Term 3')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'term'], name='academics_e_academi_ea39be_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['grade', 'subject'], name='academics_e_grade_i_9d7b66_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'academic_year'], name='academics_r_student_0485c5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['academic_year', 'term'], name='academics_r_academi_5c3497_idx'),
        ),
        migrations.AddField(
            model_name='gradescalerange',
            name='grade_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='academics.gradescale'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='fees.student'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='fees.academicyear'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='from_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_from', to='fees.grade'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='promoted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='fees.student'),
        ),
        migrations.AddField(
            model_name='studentpromotion',
            name='to_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_to', to='fees.grade'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.classsubject'),
        ),
        migrations.AlterUniqueTogether(
            name='gradescalerange',
            unique_together={('grade_scale', 'grade')},
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='academics_s_student_9c5582_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'status'], name='academics_s_date_e620eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_subject', 'day_of_week', 'start_time')},
        ),
    ]
