# Generated by Django 6.0.2 on 2026-02-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_gradescale_gradescalerange_studentattendance_and_more'),
        ('fees', '0006_alter_feebalance_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='academics.exam'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='fees.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='academics.subject'),
        ),
    ]
