# Generated by Django 5.2.1 on 2025-06-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='scanned_copy',
            field=models.ImageField(blank=True, null=True, upload_to='scanned_invoices/'),
        ),
    ]
