# Generated by Django 6.0.2 on 2026-02-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='grade_class',
            field=models.CharField(blank=True, help_text='Grade or class', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='school_year',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='student_name',
            field=models.CharField(blank=True, help_text='Student name (for school expenses)', max_length=200),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.CharField(choices=[('OFFICE', 'Office Supplies'), ('TRAVEL', 'Travel & Transportation'), ('MEALS', 'Meals & Entertainment'), ('UTILITIES', 'Utilities'), ('RENT', 'Rent'), ('EQUIPMENT', 'Equipment'), ('SERVICES', 'Professional Services'), ('TUITION', 'Tuition Fees'), ('BOOKS', 'Books & Educational Materials'), ('SCHOOL_SUPPLIES', 'School Supplies'), ('UNIFORMS', 'Uniforms & Clothing'), ('SPORTS', 'Sports & Athletics'), ('FIELD_TRIPS', 'Field Trips & Excursions'), ('LAB_FEES', 'Laboratory Fees'), ('TECHNOLOGY', 'Technology & Computer'), ('MUSIC_ARTS', 'Music & Arts Programs'), ('AFTER_SCHOOL', 'After School Programs'), ('LUNCH', 'School Lunch & Cafeteria'), ('TRANSPORTATION', 'School Transportation'), ('FUNDRAISING', 'Fundraising Expenses'), ('FACILITY', 'Facility & Maintenance'), ('STAFF_TRAINING', 'Staff Training & Development'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
