# Generated by Django 6.0.2 on 2026-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_receipt_grade_class_receipt_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('SALES', 'Sales Receipt'), ('PAYMENT', 'Payment Receipt (Receive Payment)'), ('STUDENT_FEES', 'Payment Receipt (Student Fees)'), ('EXPENSE', 'Expense Receipt'), ('REFUND', 'Refund Receipt'), ('BILL_PAYMENT', 'Bill Payment Receipt')], default='EXPENSE', max_length=20),
        ),
    ]
